### PR TITLE
Add experience at Check24

### PR DESCRIPTION
**Pull request by sergio-sastre**

### CODE REVIEW

**Review by NoNews — APPROVED** [review]
🔥

**Comment by NoNews** [comment]
Do we really need to have count of tests btw?
I suppose that authors need to update this section from time to time

But probably, it shows better what is possible to achieve via selected tools 🤔

**Review by v1sar — APPROVED** [review]
good

**Comment by sergio-sastre** [comment]
> Do we really need to have count of tests btw? I suppose that authors need to update this section from time to time
> 
> But probably, it shows better what is possible to achieve via selected tools 🤔

mmm... Yeah, maybe better to remove it form here, since it changes over time...

**Pull request merged**
